
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cart_order_db}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
product.service.id=PRODUCT-SERVICE
inventory.service.id= INVENTORY-SERVICE
services.inventory.base-url=${INVENTORY_SERVICE_URL:http://localhost:8083}
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign=DEBUG

spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=2s
