spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/inventory_db}
server.port=8083
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
product.service.id=PRODUCT-SERVICE
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign=DEBUG
